name: Rust Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Generate Docs
      run: cargo doc --no-deps --document-private-items
    
    - name: Create index.html
      run: |
        CRATE_NAME=$(cargo metadata --no-deps --format-version 1 | jq -r .packages[0].name | tr '-' '_')
        echo "<meta http-equiv=\"refresh\" content=\"0; url=$CRATE_NAME\">" > target/doc/index.html
        echo "Created index.html with redirect to $CRATE_NAME"
    
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        force_orphan: true
